plugins {
    id("org.spongepowered.gradle.vanilla")
}

base {
    archivesName = "${mod_id}-common-${minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)

    withSourcesJar()
    withJavadocJar()
}

minecraft {
    version(minecraft_version)

    if (file("src/main/resources/${mod_id}.accessWidener").exists()){
        accessWideners(file("src/main/resources/${mod_id}.accessWidener"))
    }
}

dependencies {
    // Base
    compileOnly group: 'org.spongepowered', name: 'mixin', version: mixin_version
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            group = mod_group
            artifactId = base.archivesName.get()
            version = mod_version

            from components.java
        }
    }
}